values=input("Enter the values separated by comma:")
tuple1=tuple(values.split(","))
print(tuple1[3])
print(tuple1[-4])
values=input("Enter the values separated by comma:")
tuple1=tuple(values.split(","))
print(tuple1[3])
print(tuple1[-4])
